name: Continuous Integration

on: [push, pull_request]

env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always
  MAVEN_OPTS: -Xmx4g

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup JDK 25
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: |
          21
          25
        cache: maven
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Configure unit test GPG key
      run: |
        echo -n "$UNIT_TEST_SIGNING_KEY" | base64 --decode | gpg --import
      env:
        UNIT_TEST_SIGNING_KEY: ${{ vars.UNIT_TEST_SIGNING_KEY }}
      shell: bash
    - name: Build library
      run: |
        echo "JAVA_HOME=$JAVA_HOME_21_X64" >> "$GITHUB_ENV"
        echo "$JAVA_HOME_21_X64/bin" >> "$GITHUB_PATH"
        mvn install
      working-directory: ./windowsapi-code-generator
    - name: Generate full Windows API
      run: java --class-path windowsapi-code-generator/target/test-classes:windowsapi-code-generator/target/code-generator-0.8.2.jar net.codecrete.windowsapi.special.FullBuild integration-tests/full-build/src/main/java
    - name: Build full Windows API
      run: mvn package
      working-directory: ./integration-tests/full-build
    - name: Build Maven plug-in
      run: |
        echo "JAVA_HOME=$JAVA_HOME_21_X64" >> "$GITHUB_ENV"
        echo "$JAVA_HOME_21_X64/bin" >> "$GITHUB_PATH"
        mvn install
      working-directory: ./windowsapi-maven-plugin
    - name: Build Gradle plug-in
      run: |
        echo "JAVA_HOME=$JAVA_HOME_21_X64" >> "$GITHUB_ENV"
        echo "$JAVA_HOME_21_X64/bin" >> "$GITHUB_PATH"
        ./gradlew check publish
      working-directory: ./windowsapi-gradle-plugin
    - name: Build messagebox example
      run: mvn compile
      working-directory: ./examples/messagebox
    - name: Build registry example
      run: ./gradlew --init-script ../init.gradle.kts assemble
      working-directory: ./examples/registry
    - name: Build window enumeration example
      run: ./gradlew --init-script ../init.gradle.kts assemble
      working-directory: ./examples/enum_windows
    - name: Build user notification example (Java)
      run: mvn compile
      working-directory: ./examples/user_notification_java
    - name: Build user notification example (Kotlin)
      run: mvn compile
      working-directory: ./examples/user_notification_kotlin
    - name: Build taskbar example
      run: mvn compile
      working-directory: ./examples/taskbar
    - name: Build medium story example
      run: ./gradlew --init-script ../init.gradle.kts assemble
      working-directory: ./examples/medium_story
